name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Run Lint
        run: npm run lint
        continue-on-error: true
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "dev"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
